import { StyleSheet, Platform } from 'react-native';

const BANNER_TOP_WEB = 12;
const BANNER_TOP_MOBILE = 44;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f8f9fc',
  },
  bgGradient: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    pointerEvents: 'none',
  },
  header: {
    paddingTop: 16,
    paddingHorizontal: 16,
    paddingBottom: 8,
    alignItems: 'center',
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderBottomColor: '#eee',
    marginTop: Platform.OS === 'web' ? 0 : 40,
  },
  headerInner: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
    maxWidth: 800,
    alignSelf: Platform.OS === 'web' ? 'center' : 'auto',
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: '700',
    color: '#222',
  },
  headerLabel: {
    color: '#555',
    fontWeight: '600',
  },
  headerBtn: {
    backgroundColor: '#2f6fed',
    paddingHorizontal: 10,
    paddingVertical: 0,
    borderRadius: 8,
    height: 36,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBtnText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 12,
  },
  headerBtnLogout: {
    backgroundColor: '#e53e3e',
    borderColor: '#e53e3e',
  },
  scrollContent: {
    paddingHorizontal: 16,
    paddingTop: 16,
    paddingBottom: 40,
  },
  scrollContentAuth: {
    flexGrow: 1,
    justifyContent: 'center',
    paddingTop: 24,
  },
  content: {
    width: '100%',
    maxWidth: 800,
    alignSelf: Platform.OS === 'web' ? 'center' : 'auto',
  },
  contentAuth: {
    maxWidth: Platform.OS === 'web' ? 420 : 600,
    alignSelf: 'center',
  },
  authBox: {
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    boxShadow: Platform.OS === 'web' ? '0 8px 24px rgba(0,0,0,0.08)' : undefined,
    shadowColor: Platform.OS === 'web' ? undefined : '#000',
    shadowOpacity: Platform.OS === 'web' ? undefined : 0.08,
    shadowRadius: Platform.OS === 'web' ? undefined : 12,
    shadowOffset: Platform.OS === 'web' ? undefined : { width: 0, height: 6 },
  },
  title: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    color: '#222',
  },
  modalTitle: {
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 12,
    color: '#222',
  },
  modalText: {
    fontSize: 14,
    color: '#444',
    marginBottom: 8,
  },
  section: {
    backgroundColor: '#fff',
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    shadowColor: Platform.OS === 'web' ? undefined : '#000',
    shadowOpacity: Platform.OS === 'web' ? undefined : 0.06,
    shadowRadius: Platform.OS === 'web' ? undefined : 6,
    shadowOffset: Platform.OS === 'web' ? undefined : { width: 0, height: 2 },
    elevation: 1,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#333',
  },
  sectionToggle: {
    fontSize: 16,
    color: '#777',
  },
  sectionBody: {
    marginTop: 12,
  },
  emptyListText: {
    color: '#666',
  },
  label: {
    fontSize: 13,
    color: '#444',
    marginBottom: 6,
    marginTop: 4,
  },
  labelMuted: {
    color: '#9aa0b5',
  },
  input: {
    backgroundColor: '#f7f8fc',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: Platform.OS === 'web' ? 10 : 10,
    fontSize: Platform.OS === 'web' ? 16 : 14,
    color: '#222',
    marginBottom: 8,
  },
  inputInline: {
    marginBottom: 0,
    height: Platform.OS === 'web' ? 36 : 36,
    paddingVertical: Platform.OS === 'web' ? 6 : 6,
  },
  inputDisabled: {
    opacity: 0.6,
  },
  inputEmpty: {
    backgroundColor: '#eef2ff',
  },
  inputWithIcon: {
    paddingRight: 48,
  },
  inputLinkReady: {
    color: '#1e40af',
    fontWeight: '600',
  },
  pointerCursor: Platform.OS === 'web' ? { cursor: 'pointer' } : {},
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginBottom: 8,
  },
  rowReset: {
    marginTop: 8,
    marginBottom: 8,
  },
  rowSpaceBetween: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 8,
    marginBottom: 8,
  },
  inputWrapper: {
    position: 'relative',
    marginBottom: 8,
  },
  inputIconBtn: {
    position: 'absolute',
    right: 12,
    top: '50%',
    transform: [{ translateY: -12 }],
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 6,
    minWidth: 28,
  },
  inputIconText: {
    fontSize: 16,
  },
  inputHelpError: {
    fontSize: 12,
    color: '#b91c1c',
    marginTop: 4,
    marginBottom: 6,
  },
  inputHelpArea: {
    minHeight: 22,
    marginTop: 4,
    marginBottom: 12,
  },
  btn: {
    backgroundColor: '#2f6fed',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnInline: {
    height: 36,
    paddingVertical: 6,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    minWidth: 100,
    flexShrink: 0,
  },
  btnInlineSm: {
    height: 32,
    paddingVertical: 4,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 8,
    minWidth: 88,
    flexShrink: 0,
  },
  btnInlineFluid: {
    height: 36,
    paddingVertical: 6,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 10,
    flex: 1,
  },
  btnText: {
    color: '#fff',
    fontWeight: '600',
    fontSize: 12,
    textAlign: 'center',
  },
  btnDisabled: {
    opacity: 0.5,
  },
  btnSecondary: {
    backgroundColor: '#eef2ff',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#d7defa',
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnSecondaryText: {
    color: '#2f6fed',
    fontWeight: '600',
    fontSize: 12,
    textAlign: 'center',
  },
  btnDanger: {
    backgroundColor: '#e53e3e',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  btnCapture: {
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 0,
  },
  image: {
    width: '100%',
    height: Platform.OS === 'web' ? 220 : 180,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: '#e9ecf3',
  },
  imageWrapper: {
    position: 'relative',
  },
  closeBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    backgroundColor: 'rgba(0,0,0,0.6)',
    borderRadius: 12,
    width: 24,
    height: 24,
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeBadgeText: {
    color: '#fff',
    fontWeight: '700',
    lineHeight: 20,
  },
  toggleRow: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 8,
  },
  toggleBtn: {
    flex: 1,
    backgroundColor: '#eef2ff',
    paddingVertical: 6,
    minHeight: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#d7defa',
  },
  toggleActive: {
    backgroundColor: '#2f6fed',
    borderColor: '#2f6fed',
  },
  toggleText: {
    color: '#2f6fed',
    fontWeight: '600',
    fontSize: 12,
  },
  toggleTextActive: {
    color: '#fff',
  },
  linkSmall: {
    fontSize: 12,
    color: '#2f6fed',
    textDecorationLine: 'none',
    marginTop: 4,
    marginBottom: 8,
    marginLeft: 0,
  },
  listItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    gap: 8,
  },
  listItemTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#222',
  },
  listItemSub: {
    fontSize: 12,
    color: '#666',
  },
  delBtn: {
    backgroundColor: '#e53e3e',
    borderRadius: 8,
  },
  delBtnText: {
    color: '#fff',
    fontWeight: '700',
  },
  bannerWrap: {
    position: 'absolute',
    top: Platform.OS === 'web' ? BANNER_TOP_WEB : BANNER_TOP_MOBILE,
    left: 0,
    right: 0,
    zIndex: 1000,
    elevation: 3,
    pointerEvents: 'none',
    alignItems: 'center',
  },
  btnGroup: {
    flexDirection: 'column',
    gap: 8,
    marginTop: 12,
    marginBottom: 12,
  },
  authActions: {
    flexDirection: 'column',
    gap: 1,
    marginTop: 8,
  },
  bannerBoxSuccess: {
    backgroundColor: '#e6f6ea',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    boxShadow: Platform.OS === 'web' ? '0 6px 16px rgba(0,0,0,0.08)' : undefined,
    shadowColor: Platform.OS === 'web' ? undefined : '#000',
    shadowOpacity: Platform.OS === 'web' ? undefined : 0.08,
    shadowRadius: Platform.OS === 'web' ? undefined : 10,
    shadowOffset: Platform.OS === 'web' ? undefined : { width: 0, height: 4 },
    borderWidth: Platform.OS === 'web' ? 1 : 0,
    borderColor: '#b7e3c7',
    maxWidth: Platform.OS === 'web' ? 360 : '90%',
  },
  bannerTextSuccess: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: '#166534',
    textAlign: 'center',
    fontWeight: '700',
  },
  bannerBoxWarn: {
    backgroundColor: '#fef3c7',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    boxShadow: Platform.OS === 'web' ? '0 6px 16px rgba(0,0,0,0.08)' : undefined,
    shadowColor: Platform.OS === 'web' ? undefined : '#000',
    shadowOpacity: Platform.OS === 'web' ? undefined : 0.08,
    shadowRadius: Platform.OS === 'web' ? undefined : 10,
    shadowOffset: Platform.OS === 'web' ? undefined : { width: 0, height: 4 },
    borderWidth: Platform.OS === 'web' ? 1 : 0,
    borderColor: '#fde68a',
    maxWidth: Platform.OS === 'web' ? 360 : '90%',
  },
  bannerTextWarn: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: '#7c2d12',
    textAlign: 'center',
    fontWeight: '700',
  },
  bannerBoxError: {
    backgroundColor: '#fde8e8',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 16,
    boxShadow: Platform.OS === 'web' ? '0 6px 16px rgba(0,0,0,0.08)' : undefined,
    shadowColor: Platform.OS === 'web' ? undefined : '#000',
    shadowOpacity: Platform.OS === 'web' ? undefined : 0.08,
    shadowRadius: Platform.OS === 'web' ? undefined : 10,
    shadowOffset: Platform.OS === 'web' ? undefined : { width: 0, height: 4 },
    borderWidth: Platform.OS === 'web' ? 1 : 0,
    borderColor: '#f4b7b7',
    maxWidth: Platform.OS === 'web' ? 360 : '90%',
  },
  bannerTextError: {
    fontSize: Platform.OS === 'web' ? 14 : 13,
    color: '#7f1d1d',
    textAlign: 'center',
    fontWeight: '700',
  },
  headerAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#2f6fed',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: '#dbe5ff',
  },
  headerIconBtn: {
    height: 40,
    width: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBackdrop: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.35)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 16,
  },
  modalBox: {
    width: '100%',
    maxWidth: Platform.OS === 'web' ? 420 : 600,
    backgroundColor: '#fff',
    borderRadius: 12,
    padding: 16,
    boxShadow: Platform.OS === 'web' ? '0 8px 24px rgba(0,0,0,0.16)' : undefined,
    shadowColor: Platform.OS === 'web' ? undefined : '#000',
    shadowOpacity: Platform.OS === 'web' ? undefined : 0.12,
    shadowRadius: Platform.OS === 'web' ? undefined : 16,
    shadowOffset: Platform.OS === 'web' ? undefined : { width: 0, height: 8 },
  },
  
  // Utilitários para remover inline styles
  flex1: { flex: 1 },
  centered: { justifyContent: 'center', alignItems: 'center' },
  absolute: { position: 'absolute' },
  alignStart: { alignSelf: 'flex-start' },
  mt4: { marginTop: 4 },
  mt12: { marginTop: 12 },
  ml8: { marginLeft: 8 },
  spacer24: { height: 24 },
  mb12: { marginBottom: 12 },
  wFull: { width: '100%' },
  opacity0: { opacity: 0 },

  // Env missing screen
  envContainer: { flex: 1, backgroundColor: '#121212', padding: 20, justifyContent: 'center' },
  envTitle: { color: '#fff', fontSize: 20, marginBottom: 12 },
  envText: { color: '#ccc', marginBottom: 6 },
  envWarn: { color: '#f5c518' },

  // Password checklist
  passwordChecklistWrap: { marginBottom: 20 },
  mb6: { marginBottom: 6 },
  checkItemTextOk: { fontSize: 12, color: '#16a34a' },
  checkItemTextError: { fontSize: 12, color: '#b91c1c' },
  iconOk: { color: '#16a34a' },
  iconError: { color: '#b91c1c' },
});

export default styles;